### ISSUE TITLE
Proprietary compontents: Google VR SDK

### ISSUE THREAD

**Issue by IzzySoft** [FossifyOrg/Gallery#36]
My library scanner just detected `com.google.vr` in the APK provided at releases here, which is a proprietary compontent: [Google VR SDK](https://github.com/googlevr/gvr-android-sdk). Relevant lines in the code should [be these](https://github.com/FossifyOrg/Gallery/blob/3bb21f904c7bc2754582235afc8be728edfbbfee/gradle/libs.versions.toml#L70):

```toml
sdk-videowidget = { module = "com.google.vr:sdk-videowidget", version.ref = "sdkVideowidget" }
sdk-panowidget = { module = "com.google.vr:sdk-panowidget", version.ref = "sdkPanowidget" }
```

I had hence to apply the `NonFreeComp` (non-free/proprietary compontents) to your app in my repo. Can there anything be done to avoid that? Thanks in advance!
